language: objective-c

env:
  global:
    - APPNAME="CITest"
    - 'DEVELOPER_NAME="iPhone Distribution: EL Passion Next Sp. z o.o."'
    - PROFILE_NAME=Wildcard_App_InHouse_Dist
    - 'TF_DISTRIBUTION_LISTS="CITest"'
    - TF_NOTIFY=False
    - TF_REPLACE=True
    - 'TF_BRANCH="master"'
    - secure: VEgrIu1zTxcEOCBjES43Cw2UDL5dHYfdjE8zhantimYlyIu/9MlUQUt74ZgzI1hylejcjIQh0az9A1AX4UXWC5HAyYRLmUp4emAy6dfLNmk+dOStgBm8M186Jo+SjhyN4TrHFgragRIksJYvVu2dGkxgSX48QaNULnycB+Vs4z8=
    - secure: G9aI6mr6/2nXskApKm7xg0UuUiaGcPSS6WZaxR32e8GqBc/3AUysAV8P5PpqkUtqg++9XbTasuVWV7GChhBNQrCvc/+wOa7a3ru8Sqzy6C4ozm4tLw+nRMIBC5hkA9H72wxINhVlvtQuETEKOTmkPDPpdH6Wg7KyhOfuHvjyXcE=
    - secure: Ff7ehzezrczhlLK4JBtgQGiMdeWJEdsX8gATzK6Uq4Eq/J3aPDWnRXeHBF31UPbGzKy4W5M0oFLfFd9sEqgH+T7+CVBXPquVRxAdp+D9PLN7AMaZpeGc5Lw/IprKaCTChvP3H2DbhhMUe/03cw1oWWaCIkfibGmZEXry35Ikwf8=

before_install:
  - export LANG=en_US.UTF-8
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

before_script:
  - chmod +x scripts/travis/add-key.sh
  - chmod +x scripts/travis/remove-key.sh
  - chmod +x scripts/travis/testflight.sh
  - scripts/travis/add-key.sh

script:
  - xctool clean build test -workspace CITest.xcworkspace -scheme CITest -configuration Release -sdk iphonesimulator7.1 CONFIGURATION_BUILD_DIR='~/build/test/'
  - xctool clean build -workspace CITest.xcworkspace -scheme CITest -configuration Release -sdk iphoneos7.1 CONFIGURATION_BUILD_DIR='~/build/release/'

after_script:
  - scripts/travis/remove-key.sh

after_success:
  - scripts/travis/testflight.sh
